name: Build Test
on:
  push:
    branches: [ "*" ]
    paths-ignore:
        - "**/**.md"
        - ".*"
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libwayland-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/buildDirectory -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/buildDirectory --config ${{ matrix.build_type }} --parallel 9
